### ISSUE TITLE
Firestick download problem

### ISSUE THREAD

**Issue by BlueBulldog22** [echocoderkodi/repository.echo#11]
I'll start with, I have already successfully installed this and by far you have the greatest build (repo) ever.
  When I follow the instructions to download the wizard, it states that after you "install from zip file" your notification should read, "add-on enabled."  My pop up reads "add-on installed."  From there I am to go to Install from repository.  When I chose the install tab I get a notification that reads, "The dependency on script.module.requests version 2.9.1"
  What am I doing wrong?  I feel like I have followed every step exactly the same as the other successful builds I have already done for a couple of family members as well as my own.  Any help or words of wisdom would be helpful.

**Comment by echocoderkodi** [comment]
Please read:

https://github.com/echocoderkodi/repository.echo/issues/4
