### ISSUE TITLE
Sportie error

### ISSUE THREAD

**Issue by celticmac** [echocoderkodi/repository.echo#2]
Using Echo Wizard latest build 1.89
Krypton 17.1

Python to cppexception error !!
Any help would be appreciated,
I have a screenshot of the error log.
Cheers
Mac

**Comment by echocoderkodi** [comment]
Hello,

Thank you very much for raising an issue.

Could you please let me know in as much detail as possible what you were doing to get the error.

The version of Sportie, what you were clicking etc.

If you could upload an error log via echo wizard and attach it here that would help massively.

**Comment by celticmac** [comment]
Hi I am clicking onto any of the sub menus in sport section  sky sports 1,2,3,4 etc by sport 1 ,2
Etc getting sportie error.

Cheers for the response
Sal

**Comment by echocoderkodi** [comment]
Ok please recreate the error and submit the log here.

**Comment by celticmac** [comment]
![error](https://cloud.githubusercontent.com/assets/26140480/23529077/0c707ee2-ff94-11e6-954a-95ff82c9ce7f.JPG)

Error log attacthed

**Comment by echocoderkodi** [comment]
Thank you.

Will be fixed in the next update.

Issue Closed.

**Comment by celticmac** [comment]
Thank you 👌
