### ISSUE TITLE
error reaching the url

### ISSUE THREAD

**Issue by jdig4240** [echocoderkodi/repository.echo#3]
Im getting an Echo popup "There was an error reaching the url" on every boot of kodi, Ive deleted the Echo addon data folder, checked the log, but nothing in the log related to Echo.
http://jed.one/Other%20stuff/kodi%20(5).log

**Comment by echocoderkodi** [comment]
Thank you, Will be fixed in the next update.

**Comment by echocoderkodi** [comment]
Issue is now fixed.
