### ISSUE TITLE
ECHO Wizard error

### ISSUE THREAD

**Issue by serklek** [echocoderkodi/repository.echo#4]
I have been successful up until the point where I am trying to install ECHO Wizard after downloading ECHO repository. I get a message that says "ECHO Wizard: the dependency on script.module.requesys version 2.9.1 could not be satisfied."

**Comment by echocoderkodi** [comment]
The module that you need is located in the Kodi Official Repository.

To fix this you can either delete the addons.db file in Databases or install the zip manually from here:

https://ftp.heanet.ie/mirrors/xbmc/addons/jarvis/script.module.requests/
Zip File: https://ftp.heanet.ie/mirrors/xbmc/addons/jarvis/script.module.requests/script.module.requests-2.9.1.zip

**Comment by serklek** [comment]
Do you have the file path to where the location of that addons.db file is located?

Also, if I am going to dl the zip, should I do that from the es file Explorer browser on the fire stick?

**Comment by jdig4240** [comment]
Addons27.db is located in the Userdata/Database folder in the Kodi folder on your device.

**Comment by serklek** [comment]
Yeah, don't know how to do any of that, and from your previous nessage, I already deleted that addons.db file. And it still gives me the same error message as in the beginning.

**Comment by serklek** [comment]
I was able to get the zip file mentioned above, but now that it's downloaded, how do I get it to be recognized so I can run the echo wizard install? As of now I am still getting the same script.module.request error as before.

**Comment by echocoderkodi** [comment]
Once you have that requests zip file on your box (Local storage or USB) you need to go to Install from Zip in kodi and then select that zip file.

**Comment by serklek** [comment]
Got it! Thank you! I'll let you know if I have any issues once I get a chance to look at it!

Sent via the BlackBerry Hub for Android<http://play.google.com/store/apps/details?id=com.blackberry.hub>

**Comment by serklek** [comment]
Looks like I got it working!!

Thank you for all the help!

Would anyone happen to know why this error would occur and how to avoid it in the future?

**Comment by echocoderkodi** [comment]
To fox the issue next time please follow the exact same steps as above. Its an issue that happens on Kodi quite often.
