### ISSUE TITLE
I get "ERROR Check log for more info"

### ISSUE THREAD

**Issue by mcerk02** [echocoderkodi/repository.echo#8]
App will not open, new install and has not yet worked, this is the only app I am having trouble with. Log attached

[kodi.txt](https://github.com/echocoderkodi/repository.echo/files/843136/kodi.txt)

**Comment by echocoderkodi** [comment]
You have an issue with script.module.requests

The install for that module did not install right.

There is already a ticket closed on this so please check the closed issues.

Issue closed.
