### ISSUE TITLE
Extended time taken to quit Kodi

### ISSUE THREAD

**Issue by dazw86** [echocoderkodi/repository.echo#9]
Hi guys,

I have been using echo for a while and it has been great. Then all of a sudden the time it take for Kodi to exit balloned. I've checked the logs and it seems to point to echo wizard. If I disable it, the exit speeds go back to normal.

I am by no means an expert so any help would be much appreciated.

Many thanks
[kodi.txt](https://github.com/echocoderkodi/repository.echo/files/850210/kodi.txt)

**Comment by echocoderkodi** [comment]
I can see in your log that service.py did not end after 5 seconds.

Its hard to point that as a problem as from opening kodi to closing kodi took a few minutes judging by the log.

Could you please open kodi, leave it for at least 10 minutes then upload the kodi.old.log please.

**Comment by echocoderkodi** [comment]
Echo Wizard Closed
